/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.3-19-gdac2a1116d-20251230"
#endif /* AVUTIL_FFVERSION_H */
